repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
        language_version: python2.7
    -   id: flake8
        language_version: python2.7
        args:
        - --ignore=E501
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: pretty-format-json
        language_version: python2.7
        args:
        - --autofix
        - --indent
        - '4'
    -   id: name-tests-test
        exclude: (tests/helpers/(.+).py)|(tests/fixtures/(.+).py)
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: debug-statements
    -   id: fix-encoding-pragma
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import unicode_literals
