version: '3.3'

services:
  web:
    container_name: inspire_inventory
    image: inventory:latest
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./local.env
    volumes:
      - .:/code