# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0003_dimension_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimesionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='dimension',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dfp.DimesionCategory'),
        ),
    ]
