# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0004_auto_20170214_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('hierarchy', models.TextField()),
            ],
        ),
    ]
