# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 23:26
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0007_auto_20170426_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='report_types',
            field=models.ManyToManyField(to='dfp.ReportType'),
        ),
    ]
