# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0009_community_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'communities'},
        ),
        migrations.AddField(
            model_name='report',
            name='r_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dfp.ReportType'),
        ),
    ]
