# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 22:57
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0010_auto_20170501_0549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdUnit',
        ),
        migrations.AddField(
            model_name='community',
            name='ad_unit_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
