# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0011_auto_20170506_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='report_types',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='report_types',
        ),
        migrations.AddField(
            model_name='metric',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]