# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 03:22
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0012_auto_20170524_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='email_rate',
            field=models.IntegerField(default=0),
        ),
    ]
